apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64 encoded "root"
  MYSQL_USER: cm9vdA==          # base64 encoded "root"
